
BkColor         .dword $00000000    ; [00]

PfColor0        .dword $00e4e4e4    ; [01]  cloud
PfColor1        .dword $00a49dff    ;       cloud
PfColor2        .dword $00d3d3d3    ;       cloud
PfColor3        .dword $00088814    ; [04]  mountain
PfColor4        .dword $00462075    ;       mountain
PfColor5        .dword $00300400    ;       mountain
PfColor6        .dword $000000e2    ;       mountain
PfColor7        .dword $00400000    ; [08]  water      
PfColor8        .dword $005868fc    ;       water
PfColor9        .dword $00dc241c    ;       water
PfColor10       .dword $00ebd77e    ; [0B]  mud
PfColor11       .dword $00610000    ;       mud
PfColor12       .dword $00480800    ; [0D]  grass
PfColor13       .dword $00002000    ;       grass
PfColor14       .dword $00002020    ;       grass

SprColor0       .dword $00201c00    ; [10]
SprColor1       .dword $0053b8da
SprColor2       .dword $00fc901c
SprColor3       .dword $00fc801c
SprColor4       .dword $00f85054
SprColor5       .dword $00cc3ccc
SprColor6       .dword $00c048dc
SprColor7       .dword $00a050d8

palColor0       .dword $005868fc    ; [18]
palColor1       .dword $006864fc
palColor2       .dword $004898d8
palColor3       .dword $0054a838
palColor4       .dword $001cb814
palColor5       .dword $0008ac1c
palColor6       .dword $00649028
palColor7       .dword $00ac9838
palColor8       .dword $00bc7430    ; [20]
palColor9       .dword $00484000
palColorA       .dword $00e200e2
palColorB       .dword $00404040
palColorC       .dword $00504038
palColorD       .dword $00ff1000
palColorE       .dword $00006100
palColorF       .dword $00ff00ff

                .dword $0059483c
                .dword $00006161
                .dword $004040ff
                .dword $00814020
                .dword $00ff2000
                .dword $00505050
                .dword $0059503c
                .dword $00ff2020
                .dword $005d5500
                .dword $00615944
                .dword $0061594c
                .dword $00ff3000
                .dword $00008100
                .dword $00915030
                .dword $00ff20ff
                .dword $00616161
                .dword $0069614c
                .dword $00008181
                .dword $00716900
                .dword $00ff4000
                .dword $00716955
                .dword $00ff4040
                .dword $006161ff
                .dword $00ff4800
                .dword $00a16140
                .dword $00717171
                .dword $00ff5000
                .dword $0000a100
                .dword $00857900
                .dword $00ff5900
                .dword $0000a1a1
                .dword $00b27150
                .dword $00ff6100
                .dword $00818181
                .dword $00ff6161
                .dword $00998d00
                .dword $008181ff
                .dword $0000c200
                .dword $00c28140
                .dword $00c28161
                .dword $00919191
                .dword $00ff8100
                .dword $0000c2c2
                .dword $00aea500
                .dword $00ff8181
                .dword $00d29171
                .dword $00a1a1a1
                .dword $0000e200
                .dword $00ff81ff
                .dword $00a1a1ff
                .dword $00ffa100
                .dword $00e2a181
                .dword $00c2b600
                .dword $0000e2e2
                .dword $00b2b2b2
                .dword $00ffa1a1
                .dword $00f2b291
                .dword $00c2c2c2
                .dword $00d6ce00
                .dword $00ffc200
                .dword $00c2c2ff
                .dword $00c6c6c6
                .dword $0040ff40
                .dword $0020ffff
                .dword $00ffc2a1
                .dword $00d6d6d6
                .dword $00ffe200
                .dword $0081ff81
                .dword $00e2e2ff
                .dword $00ffe2c2
                .dword $00ffe2e2
                .dword $00eaeaea
                .dword $00ffff00
                .dword $00c2ffff
                .dword $00c3b057    ; [72]
                .dword $002f0000    ; [73]
                .dword $00af69cb    ; [74]
                .dword $00ffff40    ; [75]
                .dword $00ffffff    ; [76]
                .dword $00000000    ; [77]
                .dword $00001f07    ; [78]
                .dword $00899b29    ; [79]
                .dword $00331f00    ; [7A]
                .dword $00b47e51    ; [7B]
                .dword $00115300    ; [7C]
                .dword $00b8b0ff    ; [7D]
                .dword $00041600    ; [7E]
