
BkColor         .dword $00000000    ; [00]

PfColor0        .dword $00e4e4e4    ; [01]  cloud
PfColor1        .dword $00a49dff    ;       cloud
PfColor2        .dword $00d3d3d3    ;       cloud
PfColor3        .dword $00040404    ; [04]  mountain
PfColor4        .dword $007a4416    ;       mountain
PfColor5        .dword $00a49dff    ;       mountain
PfColor6        .dword $00b9b650    ;       mountain
PfColor7        .dword $002c2492    ; [08]  water
PfColor8        .dword $003f5eac    ;       water
PfColor9        .dword $00788fc9    ;       water
PfColor10       .dword $007a4416    ; [0B]  mud
PfColor11       .dword $005c0f17    ;       mud
PfColor12       .dword $00378840    ; [0D]  grass
PfColor13       .dword $001e7027    ;       grass
PfColor14       .dword $003c7d12    ;       grass

SprColor0       .dword $00f2b04c    ; [10]  player
SprColor1       .dword $00d1d1d1    ;       player
SprColor2       .dword $008f4c0a    ;       player
SprColor3       .dword $006d0a0a    ;       player
SprColor4       .dword $006d0a0a    ;       player
SprColor5       .dword $000ad1f2    ;       player
SprColor6       .dword $00c048dc    ;       player
SprColor7       .dword $006d0a0a    ; [17]  player
SprColor8       .dword $00222222    ;       club
SprColor9       .dword $00216161    ;       club
SprColorA       .dword $004040ff    ; [1A]  gauge
SprColorB       .dword $00ff2000    ;       gauge
SprColorC       .dword $007a7990    ;       gauge
SprColorD       .dword $00505050    ;       gauge
SprColorE       .dword $00eeeeee    ; [1E]  ball
SprColorF       .dword $00cccccc    ; [1F]  aim target

palColor0       .dword $00c9a765    ; [20]  scoreboard text
palColor1       .dword $006864fc
palColor2       .dword $004898d8
palColor3       .dword $0054a838
palColor4       .dword $001cb814
palColor5       .dword $0008ac1c
palColor6       .dword $00649028
palColor7       .dword $00ac9838

palColor8       .dword $00ffffff    ; [28]
palColor9       .dword $00484000
palColorA       .dword $00e200e2
palColorB       .dword $00404040
palColorC       .dword $00504038
palColorD       .dword $00ff1000
palColorE       .dword $00006100
palColorF       .dword $00ff00ff

;--------------------------------------

                .dword $005d5500    ; [30]
                .dword $00615944
                .dword $0061594c
                .dword $00ff3000
                .dword $00008100
                .dword $00915030
                .dword $00ff20ff
                .dword $00616161
                .dword $0069614c
                .dword $00008181
                .dword $00716900
                .dword $00ff4000
                .dword $00716955
                .dword $00ff4040
                .dword $006161ff
                .dword $00ff4800
                .dword $00a16140
                .dword $00717171
                .dword $00ff5000
                .dword $0000a100
                .dword $00857900
                .dword $00ff5900
                .dword $0000a1a1
                .dword $00b27150
                .dword $00ff6100
                .dword $00818181
                .dword $00ff6161
                .dword $00998d00
                .dword $008181ff
                .dword $0000c200
                .dword $00c28140
                .dword $00c28161
                .dword $00919191
                .dword $00ff8100
                .dword $0000c2c2
                .dword $00aea500
                .dword $00ff8181
                .dword $00d29171
                .dword $00a1a1a1
                .dword $0000e200
                .dword $00ff81ff
                .dword $00a1a1ff
                .dword $00ffa100
                .dword $00e2a181
                .dword $00c2b600
                .dword $0000e2e2
                .dword $00b2b2b2
                .dword $00ffa1a1
                .dword $00f2b291
                .dword $00c2c2c2
                .dword $00d6ce00
                .dword $00ffc200
                .dword $00c2c2ff
                .dword $00c6c6c6
                .dword $0040ff40
                .dword $0020ffff
                .dword $00ffc2a1
                .dword $00d6d6d6
                .dword $00ffe200
                .dword $0081ff81
                .dword $00e2e2ff
                .dword $00ffe2c2
                .dword $00ffe2e2
                .dword $00eaeaea
                .dword $00ffff00
                .dword $00c2ffff
                .dword $00c3b057    ; [72]
                .dword $002f0000    ; [73]
                .dword $00af69cb    ; [74]
                .dword $00ffff40    ; [75]
                .dword $00ffffff    ; [76]
                .dword $00000000    ; [77]
                .dword $00001f07    ; [78]
                .dword $00899b29    ; [79]
                .dword $00331f00    ; [7A]
                .dword $00b47e51    ; [7B]
                .dword $00115300    ; [7C]
                .dword $00b8b0ff    ; [7D]
                .dword $00041600    ; [7E]
